#include <stdio.h>
void hanoi(int n, char sumber, char tujuan, char bantuan) {
    if (n == 1) {
        printf("Pindahkan cakram 1 dari tiang %c ke tiang %c\n", sumber, tujuan);
        return;
    }
    hanoi(n - 1, sumber, bantuan, tujuan);
    printf("Pindahkan cakram %d dari tiang %c ke tiang %c\n", n, sumber, tujuan);
    hanoi(n - 1, bantuan, tujuan, sumber);
}
int main() {
    int n;
    printf("Masukkan jumlah cakram: ");
    scanf("%d", &n);
    hanoi(n, 'A', 'C', 'B');
    return 0;
}

/*
Output:
Masukkan jumlah cakram: 15
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 5 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 6 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 5 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 7 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 5 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 6 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 5 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 8 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 5 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 6 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 5 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 7 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 5 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 6 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 5 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 9 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 5 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 6 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 5 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 7 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 5 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 6 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 5 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 8 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 5 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 6 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 5 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 7 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 5 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 6 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 5 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 10 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 5 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 6 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 5 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 7 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 5 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 6 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 5 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 8 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 5 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 6 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 5 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 7 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 5 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 6 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 5 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 9 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 5 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 6 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 5 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 7 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 5 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 6 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 5 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 8 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 5 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 6 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 5 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 7 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 5 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 4 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 6 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 4 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 3 dari tiang C ke tiang B
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 5 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 3 dari tiang B ke tiang A
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 2 dari tiang C ke tiang A
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 4 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
Pindahkan cakram 2 dari tiang A ke tiang B
Pindahkan cakram 1 dari tiang C ke tiang B
Pindahkan cakram 3 dari tiang A ke tiang C
Pindahkan cakram 1 dari tiang B ke tiang A
Pindahkan cakram 2 dari tiang B ke tiang C
Pindahkan cakram 1 dari tiang A ke tiang C
PS C:\Users\ASUS\OneDrive\Documents>
*/



